blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

core_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap,}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField('Заголовок', max_length=250)
    slug = models.SlugField('URL-ярлык', max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField('Текст')
    publish = models.DateTimeField('Дата публикации', default=timezone.now)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    updated = models.DateTimeField('Дата обновления', auto_now=True)
    status = models.CharField('Статус', max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month, self.publish.day, self.slug])

    tags = TaggableManager(verbose_name='Тег')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField('Имя', max_length=80)
    email = models.EmailField('Почта')
    body = models.TextField('Комментарии')
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    updated = models.DateTimeField('Дата обновления', auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Комментарий {self.name} под постом {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=25)
    email = forms.EmailField(label='Ваша почта')
    to = forms.EmailField(label='Почта получателя')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='Комментарии')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(label='Запрос')

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.conf import settings
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts,
                                                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts,
                                                     })


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) рекомендует вам новость {post.title}"
            message = f'Прочитайте "{post.title}" {post_url}\n\n{cd["name"]} комментарии:{cd["comments"]}'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!doctype html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
        <h2>Мой блог</h2>
        <p>Это мой блог. Количество написанных мной постов: {% total_posts %}</p>
        <p><a href="{% url 'blog:post_feed' %}">Подпишитесь на мою RSS-ленту</a></p>
        <h3>Последние посты.</h3>
        {% show_latest_posts 3 %}
        <h3>Самые комментируемые посты</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Опубликовано {{ post.publish }} автор: {{ post.author }}</p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Поделиться этим постом</a>
    </p>
    <h1>
        Похожие посты
    </h1>
    {% for sim_post in similar_posts %}
    <p>
        <a href="{{ sim_post.get_absolute_url }}">{{ sim_post }}</a>
    </p>
    {% empty %}
        Нету похожих постов
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} комментарий
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} автор: {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
    <p>Нет комментариев</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Комментарий был успешно добавлен.</h2>
    {% else %}
        <h2>Добавить комментарий</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}Мой Блог{% endblock %}
{% block content %}
    <h1>Мой блог</h1>
    {% if tag %}
        <h2>Посты с тегом "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            Теги:
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Опубликовано {{ post.publish }} автор: {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Посты содержащие "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
             Количество найденных результатов: {{ total_results }}
            {% endwith %}
        </h3>
            {% for post in results %}
                <h4>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h4>
                    {{ post.body|truncatewords:5 }}
            {% empty %}
                <p>Нет результатов по запросу "{{ query }}"</p>
            {% endfor %}
            <p>
                <a href="{% url 'blog:post_search' %}">Поиск заново</a>
            </p>
    {% else %}
        <h1>Поиск по постам</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Поделиться{% endblock %}
{% block content %}
  {% if sent %}
  <h1>Письмо успешно отправлено на e-mail</h1>
  <p>"{{ post.title }}" успешно отправлен на почту {{ form.cleaned_data }}.</p>
  {% else %}
  <h1>Поделиться новостью "{{ post.title }}" через e-mail</h1>
  <form action="." method="post">

    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Отправить письмо">

  </form>

  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Предыдущая страница</a>
    {% endif %}
    <span class="current">
      Страница {{ page.number }} из {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Следующая страница</a>
    {% endif %}
  </span>
</div>